<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [1]:
import numpy as np
from numpy import array

start = -2
end = 10
cd = 1.5

def generate():
    # your code here
    aparr = np.arange(start, end, cd)
    aparr[(aparr >= 2) & (aparr <7)] *= -1
    return aparr # return modified array
print(generate())

[-2.  -0.5  1.  -2.5 -4.  -5.5  7.   8.5]


### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [2]:
import numpy as np
def generate():
    # your code
    vect = np.random.randn(7)
    print(vect)
    vect[vect == vect.max()] = 2
    vect[vect == vect.min()] = 7
    vect[::-1].sort()
    return vect# your array
generate()

[ 0.48735416 -0.35302101 -0.50407934 -0.34997067  0.61221341 -1.56316198
 -1.80456467]


array([ 7.        ,  2.        ,  0.48735416, -0.34997067, -0.35302101,
       -0.50407934, -1.56316198])

### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2().

In [3]:
import numpy as np
def generate():
    # your code here
    cartArr = np.random.randint(10,20+1,(7,2))
    polArr = np.ones((7,2),dtype=float)
    polArr[:,0] = (cartArr[:,0]**2+cartArr[:,1]**2)**.5
    polArr[:,1] = (np.arctan2(cartArr[:,1],cartArr[:,0])*180)/np.pi
    # print out both matrices
    print(cartArr)
    print(polArr)
    return None
generate()

[[16 11]
 [12 20]
 [15 10]
 [19 20]
 [20 19]
 [11 16]
 [20 12]]
[[19.41648784 34.50852299]
 [23.32380758 59.03624347]
 [18.02775638 33.69006753]
 [27.58622845 46.46880071]
 [27.58622845 43.53119929]
 [19.41648784 55.49147701]
 [23.32380758 30.96375653]]


### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [4]:
import numpy as np

length = 30
start = 5
step = 2

def generate(start, length, step):
    # your code here
    num_seq = np.arange(start,(length*step+start), step)
    print(len(num_seq))
    return num_seq# array created by you, i.e. num_seq
generate(start, length, step)

30


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63])

### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4.
HINT: Use reshape and transpose function.

In [5]:
import numpy as np
def generate():
    # your code here
    arr1 = np.arange(0,9,1)
    arr1 = arr1.reshape(3,3)
    print('Original 3*3 array : \n',arr1)
    arr2 = arr1.T
    print('Transposed 3*3 array : \n',arr2)
    arr3 = np.ones((1,3))
    print('ones 1*3 array : \n',arr3)
    arr4 = arr2-arr3
    return arr4# finally created array i.e arr4
generate()

Original 3*3 array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Transposed 3*3 array : 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
ones 1*3 array : 
 [[1. 1. 1.]]


array([[-1.,  2.,  5.],
       [ 0.,  3.,  6.],
       [ 1.,  4.,  7.]])

### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Print it out. Hint: use pd.date_range.

In [1]:
import pandas as pd
import numpy as np
pd.offsets.BDay()
def generate():
    # Your code here
    indx = pd.date_range(start='2016-01-01',end='2016-12-31',freq=pd.offsets.BDay())
    data = list(np.random.randn(len(indx)))
    bus_2k16 = pd.Series(data,index=indx)
    # print out bus_2k16
    print(bus_2k16)
    return None
generate()

2016-01-01   -0.120152
2016-01-04   -0.791982
2016-01-05    1.135717
2016-01-06   -1.813553
2016-01-07    1.792878
2016-01-08    0.803114
2016-01-11   -1.054950
2016-01-12    0.352019
2016-01-13   -1.533352
2016-01-14   -1.199496
2016-01-15    1.067790
2016-01-18    0.857432
2016-01-19    0.012398
2016-01-20    1.016046
2016-01-21    0.041445
2016-01-22   -0.042845
2016-01-25   -0.761226
2016-01-26    0.876615
2016-01-27    0.047948
2016-01-28    0.083540
2016-01-29    0.243283
2016-02-01   -0.306469
2016-02-02   -1.538000
2016-02-03   -0.345632
2016-02-04   -0.156734
2016-02-05    0.768560
2016-02-08    2.088120
2016-02-09    0.203972
2016-02-10    1.068957
2016-02-11    0.396654
                ...   
2016-11-21    0.783099
2016-11-22   -0.781639
2016-11-23    1.474147
2016-11-24    0.717804
2016-11-25   -1.294276
2016-11-28   -1.052042
2016-11-29    0.745686
2016-11-30   -1.317917
2016-12-01   -0.180128
2016-12-02    0.202235
2016-12-05    0.538478
2016-12-06   -0.594738
2016-12-07 

###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Sunday.

In [7]:
import pandas as pd
def generate():
    # Your code here
#     indx = pd.date_range(start='01/01/2016',end='31/12/2016',freq=pd.offsets.BDay())
    indx = pd.date_range(start='01/01/2016',end='31/12/2016')
    data = {'numbers':list(np.random.randn(len(indx)))}
    bus_2k16 = pd.DataFrame(data,index=indx)
    means = bus_2k16.groupby(bus_2k16.index.month)['numbers'].mean()
    sum_days = (bus_2k16.groupby(bus_2k16.index.dayofweek)['numbers'].sum())
    sum_sundays = (bus_2k16.groupby(bus_2k16.index.dayofweek)['numbers'].sum())[6]
#     print(bus_2k16)
    # print out mean
    print('Mean values for each calendar month')
    print(means)
    # print out sum of the values in bus_2k16 for every Sunday.
    print('\nSum of values for each day of the week')
    print(sum_days)
    print('\nSum of values for sundays in the year')
    print(sum_sundays)
    return None
generate()

Mean values for each calendar month
1    -0.145353
2    -0.209150
3    -0.067895
4    -0.176896
5     0.152142
6     0.091166
7     0.179533
8    -0.126074
9    -0.110868
10    0.149763
11   -0.225463
12    0.028878
Name: numbers, dtype: float64

Sum of values for each day of the week
0    10.966123
1    -6.603986
2     7.705801
3   -12.025112
4   -15.467642
5     2.910978
6    -0.912511
Name: numbers, dtype: float64

Sum of values for sundays in the year
-0.9125108716280257


### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [8]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate(df):
    # write your code here
    fs = lambda x : x.split('_')
    fc = lambda x : x.capitalize()
    fse = lambda x : pd.Series(x)
    temp = pd.DataFrame((df['From_To'].apply(fc).apply(fs).apply(fse)))
    temp.columns =['From','To']
#     temp['From'] = temp['From'].apply(fc)
    temp['To'] = temp['To'].apply(fc)
    df = df.drop('From_To', axis=1)
    temp = temp.join(df, how='left')
    return temp# your temporary variable i.e temp.
generate(df)

From         To  FlightNumber  RecentDelays              Airline
0    London      Paris       10045.0      [23, 47]               KLM(!)
1    Madrid      Milan           NaN            []    <Air France> (12)
2    London  Stockholm       10065.0  [24, 43, 87]  (British Airways. )
3  Budapest      Paris           NaN          [13]       12. Air France
4  Brussels     London       10085.0      [67, 32]          "Swiss Air"

### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has. 
Hint: use idxmin method.

In [13]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))

print(df)
def generate():
    # your code here
    temp_min = df.sum(0).idxmin()
    temp_max = df.sum(0).idxmax()
    temp_sums = df.sum(0)
    print('\nSum of columns in the given DataFrame\n',temp_sums)
    uniq_rows = len(df.drop_duplicates())
    # print out that column's label which has the smallest sum
    print('\ncolumn \'{}\' has the smallest sum.\n And column\'{}\' has largest sum.'.format(temp_min, temp_max))
    # Also count the number of unique rows the dataframe has.
    print('The DataFrame has {} unique rows'.format(uniq_rows))
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.443809  0.738470  0.944624  0.454187  0.678744  0.462028  0.929834   
1  0.736657  0.719845  0.224513  0.968259  0.507672  0.608917  0.758537   
2  0.701438  0.312765  0.573510  0.412552  0.498228  0.134333  0.149451   
3  0.343741  0.358004  0.291508  0.198921  0.594308  0.066710  0.331939   

          x         y         z  
0  0.184814  0.309645  0.960772  
1  0.181860  0.110551  0.858412  
2  0.254931  0.335232  0.696285  
3  0.384009  0.889780  0.016962  

Sum of columns in the given DataFrame
 q    2.225645
r    2.129085
s    2.034156
t    2.033919
u    2.278953
v    1.271988
w    2.169762
x    1.005613
y    1.645208
z    2.532432
dtype: float64

column 'x' has the smallest sum.
 And column'z' has largest sum.
The DataFrame has 4 unique rows


### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element .
Hint: use drop_duplicates and sub methods

In [11]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    # your code here
    meanVal = df.mean()
    df2 = df - df.mean()
    # Print out the dataframe with filtered out rows which contain the same integer as the row immediately above
    print('Dataframe after filtered out rows which contain the same integer as the row immediately above')
    print(df[df.duplicated()])
    # Print out the dataframe after subtracting the mean of all integers from each element
    print('Dataframe after deleting mean {} from each element'.format(meanVal[0]))
    print(df2)
    return None
generate()

Dataframe after filtered out rows which contain the same integer as the row immediately above
    int
2     2
6     5
7     5
10    7
Dataframe after deleting mean 4.2727272727272725 from each element
         int
0  -3.272727
1  -2.272727
2  -2.272727
3  -1.272727
4  -0.272727
5   0.727273
6   0.727273
7   0.727273
8   1.727273
9   2.727273
10  2.727273
