<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [1]:
import numpy as np
def generate():
    # Write your code here
    vect = np.arange(0,7)
    vect[2] = 2
    vect[6] = 2
    return vect# your variable 
generate()

array([0, 1, 2, 3, 4, 5, 2])

### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [2]:
import numpy as np
from numpy import random
size = 9
maxVal = 4
def generate(s,m):
    # Write your code here
    vect1 = np.random.random((s))*m
    print(vect1)
    vect2 = np.random.rand(s)*m
    print(vect2)
    return vect1, vect2  # your variable
v1, v2 = generate(size,maxVal)

print(v1)
print(v2)

[3.72274149 1.01474841 0.26677194 1.628413   1.08135349 0.42344034
 3.97419788 0.27281584 3.09938881]
[2.04745976 2.42066862 2.2642034  2.56719115 1.71593714 1.40514576
 0.22939009 3.71829232 0.68844526]
[3.72274149 1.01474841 0.26677194 1.628413   1.08135349 0.42344034
 3.97419788 0.27281584 3.09938881]
[2.04745976 2.42066862 2.2642034  2.56719115 1.71593714 1.40514576
 0.22939009 3.71829232 0.68844526]


### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [3]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate(series):
    # your code
    f = lambda x: x.capitalize()
    series = series.apply(f)
#     print(type(series))
    return series# your variable for new series
s = generate(series) 
print(s)

0              How
1               To
2            Learn
3    Data science?
dtype: object


### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [4]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
print(matrix_fab)
# row_mean = matrix_fab.mean(axis=1)
# print(row_mean)
def generate(m):
    # Write your code here
    matrix_sub = m-m.mean(axis=1).reshape((3,1))
    print(matrix_sub)
    matrix_norm = matrix_sub/(m.max()*2)
    # print matrix_norm
    print(matrix_norm)
    return None
generate(matrix_fab)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[-0.0625  0.      0.0625]
 [-0.0625  0.      0.0625]
 [-0.0625  0.      0.0625]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [5]:
import numpy as np
def generate():
    # Write your code here
    vect = np.random.random((1,12))*2
    vect = vect.reshape(4,3)
    print(vect.shape, type(vect))
    return vect # your variable
generate()

(4, 3) <class 'numpy.ndarray'>


array([[0.87363921, 0.9750563 , 1.37805147],
       [0.96801832, 1.06434163, 1.07243795],
       [0.1901465 , 1.52899305, 0.68940501],
       [1.69405873, 0.21779204, 1.3289458 ]])

### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [6]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate(d,l):
    # Write your code here
    df = pd.DataFrame(d,l)
    # option 1 : Using transpose of DataFrame
    dft = df.transpose()
    nans1 = dft.loc[:,dft.isnull().any()].transpose()
    print(nans1)
    
    #option 2 : using row axis for any() function
    nans2 = df.loc[df.isnull().any(1),:]
    print(nans2)

    
    return [nans1, nans2]   # your variable
generate(data, labels)


  animal  age visits priority
d    dog  NaN      3      yes
h    cat  NaN      1      yes
  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


[  animal  age visits priority
 d    dog  NaN      3      yes
 h    cat  NaN      1      yes,   animal  age  visits priority
 d    dog  NaN       3      yes
 h    cat  NaN       1      yes]

### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [7]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
def generate(d,l):
    # write your code here
    df = pd.DataFrame(d,l)
    f = lambda x: x == 'dog' and 'Labrador' or x
    df['animal'] = df['animal'].apply(f)
    df.loc[('d'),('age')] = 2.7
#     option 1 : Using df.groupby()
    mean_age1 = df.groupby('animal')['age'].mean()
    
#     option 2 : Using filter for df 
    mean_age2 = {'snake':df[df['animal'] == 'snake']['age'].mean(), 
               'cat': df[df['animal'] == 'cat']['age'].mean(),
               'Labrador': df[df['animal'] == 'Labrador']['age'].mean()}
    
    # Also print df
    print(df)
    return mean_age1, mean_age2# your variable i.e mean_age
mean_age1, mean_age2 = generate(data, labels)

print(mean_age1)
print(mean_age2)

     animal  age  visits priority
a       cat  2.5       1      yes
b       cat  3.0       3      yes
c     snake  0.5       2       no
d  Labrador  2.7       3      yes
e  Labrador  5.0       2       no
f       cat  2.0       3       no
g     snake  4.5       1       no
h       cat  NaN       1      yes
i  Labrador  7.0       2       no
j  Labrador  3.0       1       no
animal
Labrador    4.425
cat         2.500
snake       2.500
Name: age, dtype: float64
{'snake': 2.5, 'cat': 2.5, 'Labrador': 4.425}


### 8.  From the given dataframe get the positions where values of two columns match?

In [8]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate(df):
    # your code here
    print(df)
    matching = df[df['fruit1'] == df['fruit2']].index
    print(matching)
    return None
generate(df)

   fruit1  fruit2
0  orange  banana
1  banana  banana
2  banana  orange
3  orange  banana
4   apple  orange
5  banana   apple
6   apple  orange
7   apple   apple
8  orange  orange
9  banana  orange
Int64Index([1, 7, 8], dtype='int64')


### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [9]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate(s):
    # your code here
    mulFour = s[s%4 == 0].index
    # print(series)
    print(s)
    return mulFour# your variable
generate(series)

0    5
1    6
2    7
3    1
4    2
5    9
6    5
dtype: int32


Int64Index([], dtype='int64')

### 10. Stack two given series vertically and horizontally ? Print out both.

In [10]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate(s1,s2):
    # your code 
    df = pd.DataFrame({'s1':s1,'s2':s2},columns=['s1','s2'])
    print(df.stack())
    print(df.unstack())
    print(df)
    # print out both vertically and horizontally stacked series.
    return None
generate(series1, series2)

0  s1    0
   s2    a
1  s1    1
   s2    b
2  s1    2
   s2    c
3  s1    3
   s2    d
4  s1    4
   s2    e
dtype: object
s1  0    0
    1    1
    2    2
    3    3
    4    4
s2  0    a
    1    b
    2    c
    3    d
    4    e
dtype: object
   s1 s2
0   0  a
1   1  b
2   2  c
3   3  d
4   4  e
